# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data_transfer.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x64\x61ta_transfer.proto\"\x07\n\x05\x45mpty\"\x99\x01\n\x0c\x44\x61taResponse\x12\r\n\x05image\x18\x01 \x01(\x0c\x12\r\n\x05label\x18\x02 \x01(\x0c\x12\r\n\x05pproc\x18\x03 \x01(\x05\x12\r\n\x05\x66name\x18\x04 \x01(\t\x12\x10\n\x08pil_mode\x18\x05 \x01(\t\x12\r\n\x05width\x18\x06 \x01(\x05\x12\x0e\n\x06height\x18\x07 \x01(\x05\x12\r\n\x05shape\x18\x08 \x03(\x05\x12\r\n\x05\x64type\x18\t \x01(\t\"9\n\x0b\x44\x61taRequest\x12\r\n\x05\x66name\x18\x01 \x01(\t\x12\r\n\x05pproc\x18\x02 \x01(\x05\x12\x0c\n\x04size\x18\x03 \x01(\x05\x32\xd5\x01\n\x0c\x44\x61taTransfer\x12/\n\x0eget_data_nooff\x12\x0c.DataRequest\x1a\r.DataResponse\"\x00\x12\x30\n\x0fget_data_alloff\x12\x0c.DataRequest\x1a\r.DataResponse\"\x00\x12\x30\n\x0fget_data_piloff\x12\x0c.DataRequest\x1a\r.DataResponse\"\x00\x12\x30\n\x0fget_data_sophon\x12\x0c.DataRequest\x1a\r.DataResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'data_transfer_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_EMPTY']._serialized_start=23
  _globals['_EMPTY']._serialized_end=30
  _globals['_DATARESPONSE']._serialized_start=33
  _globals['_DATARESPONSE']._serialized_end=186
  _globals['_DATAREQUEST']._serialized_start=188
  _globals['_DATAREQUEST']._serialized_end=245
  _globals['_DATATRANSFER']._serialized_start=248
  _globals['_DATATRANSFER']._serialized_end=461
# @@protoc_insertion_point(module_scope)
