# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import data_transfer_pb2 as data__transfer__pb2


class DataTransferStub(object):
    """rpc get_samples(Empty) returns (stream Sample) {}; 
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get_data_nooff = channel.unary_unary(
                '/DataTransfer/get_data_nooff',
                request_serializer=data__transfer__pb2.DataRequest.SerializeToString,
                response_deserializer=data__transfer__pb2.DataResponse.FromString,
                )
        self.get_data_alloff = channel.unary_unary(
                '/DataTransfer/get_data_alloff',
                request_serializer=data__transfer__pb2.DataRequest.SerializeToString,
                response_deserializer=data__transfer__pb2.DataResponse.FromString,
                )
        self.get_data_piloff = channel.unary_unary(
                '/DataTransfer/get_data_piloff',
                request_serializer=data__transfer__pb2.DataRequest.SerializeToString,
                response_deserializer=data__transfer__pb2.DataResponse.FromString,
                )
        self.get_data_sophon = channel.unary_unary(
                '/DataTransfer/get_data_sophon',
                request_serializer=data__transfer__pb2.DataRequest.SerializeToString,
                response_deserializer=data__transfer__pb2.DataResponse.FromString,
                )


class DataTransferServicer(object):
    """rpc get_samples(Empty) returns (stream Sample) {}; 
    """

    def get_data_nooff(self, request, context):
        """rpc put_stats(ImageStats) returns (Empty) {}; 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_data_alloff(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_data_piloff(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_data_sophon(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DataTransferServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'get_data_nooff': grpc.unary_unary_rpc_method_handler(
                    servicer.get_data_nooff,
                    request_deserializer=data__transfer__pb2.DataRequest.FromString,
                    response_serializer=data__transfer__pb2.DataResponse.SerializeToString,
            ),
            'get_data_alloff': grpc.unary_unary_rpc_method_handler(
                    servicer.get_data_alloff,
                    request_deserializer=data__transfer__pb2.DataRequest.FromString,
                    response_serializer=data__transfer__pb2.DataResponse.SerializeToString,
            ),
            'get_data_piloff': grpc.unary_unary_rpc_method_handler(
                    servicer.get_data_piloff,
                    request_deserializer=data__transfer__pb2.DataRequest.FromString,
                    response_serializer=data__transfer__pb2.DataResponse.SerializeToString,
            ),
            'get_data_sophon': grpc.unary_unary_rpc_method_handler(
                    servicer.get_data_sophon,
                    request_deserializer=data__transfer__pb2.DataRequest.FromString,
                    response_serializer=data__transfer__pb2.DataResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'DataTransfer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DataTransfer(object):
    """rpc get_samples(Empty) returns (stream Sample) {}; 
    """

    @staticmethod
    def get_data_nooff(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DataTransfer/get_data_nooff',
            data__transfer__pb2.DataRequest.SerializeToString,
            data__transfer__pb2.DataResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def get_data_alloff(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DataTransfer/get_data_alloff',
            data__transfer__pb2.DataRequest.SerializeToString,
            data__transfer__pb2.DataResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def get_data_piloff(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DataTransfer/get_data_piloff',
            data__transfer__pb2.DataRequest.SerializeToString,
            data__transfer__pb2.DataResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def get_data_sophon(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DataTransfer/get_data_sophon',
            data__transfer__pb2.DataRequest.SerializeToString,
            data__transfer__pb2.DataResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
